/**
 * The Send SMS auth hook: Supabase generates the code, this delivers it.
 *
 * Supabase Auth calls this over HTTPS whenever it needs an SMS OTP sent. The
 * code is already generated and already stored by Auth - this function's only
 * job is delivery, and getting that boundary right is what keeps verification
 * out of here entirely. Nothing in this file decides whether a code is correct.
 *
 * ## ⚠️ Nothing calls this yet
 *
 * PINGO does not use Supabase phone OTP. Phone sign-in derives an address -
 * `919876543210@phone.pingo.chat` - and uses a password, and `auth-service.ts`
 * says why in as many words: "phone sign-in works on a project with no SMS
 * provider configured and no SMS budget."
 *
 * So this hook fires only once two things are true: the phone provider is on,
 * and the client calls `signInWithOtp({ phone })` instead of the derived
 * address. Until then it is deployed and idle, which costs nothing and is the
 * right order - the delivery path is worth having working *before* anybody
 * depends on it.
 *
 * ## The signature is the whole of the authentication
 *
 * `verify_jwt` is off, because the caller is Supabase Auth and it has no user
 * session - the same arrangement as `push-send`, for the same reason. What
 * replaces it is a Standard Webhooks signature over the raw body. That is why
 * the body is read as text and only parsed after it verifies: parsing first and
 * verifying the parsed object would leave a gap between what was signed and
 * what is acted on.
 *
 * Without this, the endpoint is an open SMS sender pointed at a paid account.
 *
 * ## Nothing sensitive is logged
 *
 * Not the OTP, not the phone number, not the API key, not the request body. A
 * log line containing an OTP is a log line that defeats the OTP, and these logs
 * are readable by anyone with dashboard access. Failures record what failed and
 * the provider's status code, which is enough to fix a problem and not enough
 * to impersonate anybody.
 */
import { Webhook } from 'https://esm.sh/standardwebhooks@1.0.0';

/**
 * The three secrets, and none of them are in this file.
 *
 * `SEND_SMS_HOOK_SECRET` is generated by Supabase when the hook is created and
 * arrives prefixed `v1,whsec_`; the library wants the base64 that follows.
 */
const HOOK_SECRET = Deno.env.get('SEND_SMS_HOOK_SECRET');
const TWOFACTOR_API_KEY = Deno.env.get('TWOFACTOR_API_KEY');

/**
 * A DLT-approved template name, if the account uses one.
 *
 * Optional: 2Factor accepts the URL without it and falls back to the account
 * default. Named rather than hardcoded because the approved template is an
 * account-level fact that changes without this code changing.
 */
const TWOFACTOR_TEMPLATE = Deno.env.get('TWOFACTOR_TEMPLATE_NAME');

/**
 * `SMS` or `VOICE`. 2Factor reads the code out loud on the voice route.
 *
 * This is a secret rather than something the caller picks, because Supabase's
 * Send SMS hook payload has no channel field - it carries `user` and
 * `sms.otp`, and nothing else - so there is no per-request choice to honour
 * even if a screen offered one. Switching it here re-routes every send.
 *
 * The template is an SMS-only concept; the voice route takes the number and
 * the code and nothing more.
 */
const CHANNEL = Deno.env.get('TWOFACTOR_CHANNEL')?.trim().toUpperCase() === 'VOICE'
  ? 'VOICE'
  : 'SMS';

/**
 * Long enough for a slow gateway, short enough that Auth is not left hanging.
 *
 * Supabase Auth waits on this response before it answers the user, so a hook
 * with no timeout turns one slow provider into a sign-in that never returns.
 */
const PROVIDER_TIMEOUT_MS = 10_000;

/** What Supabase Auth reads on failure. The status code is repeated inside it. */
function failure(httpCode: number, message: string): Response {
  return new Response(JSON.stringify({ error: { http_code: httpCode, message } }), {
    status: httpCode,
    headers: { 'Content-Type': 'application/json' },
  });
}

/** Success is an empty object and a 200. Auth reads nothing else. */
const OK = () =>
  new Response(JSON.stringify({}), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });

interface HookPayload {
  user?: { id?: string; phone?: string };
  sms?: { otp?: string };
}

/**
 * Digits only, `+` removed.
 *
 * 2Factor takes the number as a path segment, so a `+` would have to be encoded
 * and an unencoded one silently changes the path. Indian numbers reach it
 * happily as `919876543210`; the country code is left alone rather than
 * stripped, because guessing at it is how a number in one country gets sent to
 * a different one.
 */
function toProviderNumber(phone: string): string {
  return phone.replace(/\D/g, '');
}

Deno.serve(async (request) => {
  if (request.method !== 'POST') return failure(405, 'Method not allowed.');

  if (!HOOK_SECRET) {
    console.error('[send-sms] SEND_SMS_HOOK_SECRET is not set');
    return failure(500, 'Hook is not configured.');
  }
  if (!TWOFACTOR_API_KEY) {
    console.error('[send-sms] TWOFACTOR_API_KEY is not set');
    return failure(500, 'SMS provider is not configured.');
  }

  /*
   * Read as text and verify before parsing. The signature covers these exact
   * bytes, so parsing first would mean acting on an object nobody signed.
   */
  const raw = await request.text();
  const headers = Object.fromEntries(request.headers);

  let payload: HookPayload;
  try {
    const webhook = new Webhook(HOOK_SECRET.replace('v1,whsec_', ''));
    payload = webhook.verify(raw, headers) as HookPayload;
  } catch {
    // No detail: a caller who fails this does not get told which part failed.
    console.error('[send-sms] signature rejected');
    return failure(401, 'Invalid signature.');
  }

  const phone = payload.user?.phone?.trim() ?? '';
  const otp = payload.sms?.otp?.trim() ?? '';

  if (!phone || !otp) {
    console.error('[send-sms] payload missing phone or otp');
    return failure(400, 'Payload is missing a phone number or a code.');
  }

  const number = toProviderNumber(phone);
  if (number.length < 8 || number.length > 15) {
    // E.164 allows 15 digits at most; below eight is not a number anywhere.
    console.error('[send-sms] phone number is not a plausible length');
    return failure(400, 'Phone number is not usable.');
  }
  if (!/^\d{4,8}$/.test(otp)) {
    console.error('[send-sms] otp is not the expected shape');
    return failure(400, 'Code is not usable.');
  }

  /*
   * The key is a path segment, which is 2Factor's design and not a choice made
   * here. It is why nothing in this function logs a URL.
   */
  const url =
    `https://2factor.in/API/V1/${encodeURIComponent(TWOFACTOR_API_KEY)}` +
    `/${CHANNEL}/${encodeURIComponent(number)}/${encodeURIComponent(otp)}` +
    (CHANNEL === 'SMS' && TWOFACTOR_TEMPLATE
      ? `/${encodeURIComponent(TWOFACTOR_TEMPLATE)}`
      : '');

  let response: Response;
  try {
    response = await fetch(url, {
      method: 'GET',
      signal: AbortSignal.timeout(PROVIDER_TIMEOUT_MS),
    });
  } catch (cause) {
    // A timeout and a dead network look the same to Auth, and both mean "no".
    const timedOut = cause instanceof DOMException && cause.name === 'TimeoutError';
    console.error(`[send-sms] provider unreachable${timedOut ? ' (timeout)' : ''}`);
    return failure(502, timedOut ? 'SMS provider timed out.' : 'SMS provider unreachable.');
  }

  if (!response.ok) {
    console.error(`[send-sms] ${CHANNEL} refused with ${response.status}`);
    return failure(502, `SMS provider refused (${response.status}).`);
  }

  /*
   * 2Factor answers `{"Status":"Success","Details":"<session id>"}` on success.
   * The exact shape of its failure body is not documented anywhere I could
   * verify, so this treats anything that is not an explicit Success as a
   * failure rather than pattern-matching on error text that may change. The
   * `Details` value is a session id used by the VERIFY endpoint, which PINGO
   * does not call - Supabase Auth verifies the code itself - so it is dropped
   * rather than stored.
   */
  const body = (await response.json().catch(() => null)) as { Status?: string } | null;

  if (body?.Status !== 'Success') {
    console.error(`[send-sms] ${CHANNEL} did not report success`);
    return failure(502, 'SMS provider did not accept the message.');
  }

  return OK();
});
