-- PINGO — end-to-end encryption, without touching anything that already exists.
--
-- See docs/e2ee-architecture.md for why the construction is what it is. This is
-- only the storage it needs.
--
-- ## Nothing here migrates a single row
--
-- Both columns are nullable and default to null, so every message written
-- before this migration keeps exactly the bytes it has. `encryption is null`
-- *means* legacy, and it means that for free — no backfill, no rewrite, no
-- window during which a thread is half one thing and half another.
--
-- Detection is this column and never a guess at the content. A heuristic —
-- "does the body look like base64?" — misfires on a message that happens to,
-- and the failure mode is somebody's chat rendering as garbage.

alter table public.messages
  add column if not exists encryption text;

alter table public.messages
  add column if not exists envelope jsonb;

do $$
begin
  alter table public.messages
    add constraint messages_encryption_version
    check (encryption is null or encryption = 'v1');
exception
  when duplicate_object then null;
end;
$$;

/*
 * A row is either wholly legacy or wholly encrypted.
 *
 * An encrypted body with no envelope is a message nobody can ever read, and it
 * would be written by a client that failed halfway. Refusing it here means the
 * failure surfaces at the send rather than as an undecryptable bubble
 * discovered later, when the plaintext is long gone.
 */
do $$
begin
  alter table public.messages
    add constraint messages_envelope_matches_encryption
    check ((encryption is null and envelope is null) or (encryption = 'v1' and envelope is not null));
exception
  when duplicate_object then null;
end;
$$;

-- ---------------------------------------------------------------------------
-- Device keys
-- ---------------------------------------------------------------------------
--
-- One row per device, not per user. A sender wraps the message key once for
-- each device the recipient has, which is what makes multi-device an addition
-- rather than a redesign — a new device publishes a row and future messages
-- include it.
--
-- Only the *public* half is ever here. The private key is generated on the
-- device as a non-extractable CryptoKey: the platform will use it and refuses
-- to serialise it, so no bug, no XSS and no careless line can put it in a
-- request. That guarantee is enforced by the browser rather than by our care.

create table if not exists public.device_keys (
  /*
   * Generated by the device, not the database.
   *
   * The device has to name itself before it can publish anything, and a
   * server-assigned id would need a round trip in the middle of first-run key
   * generation — which is exactly when the app should be doing nothing else.
   */
  device_id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,

  /** SPKI, base64. P-256 — see the architecture note on why not X25519. */
  public_key text not null,

  created_at timestamptz not null default now(),
  /** Touched on each launch, so a long-dead device can be pruned later. */
  last_seen_at timestamptz not null default now(),

  constraint device_keys_public_key_length check (char_length(public_key) between 32 and 512)
);

create index if not exists device_keys_user_idx on public.device_keys (user_id);

alter table public.device_keys enable row level security;

/*
 * World-readable, deliberately.
 *
 * A public key is public: anyone who wants to send you a message needs it
 * before you have ever spoken, so gating this on a friendship or a shared
 * conversation would mean the first message to a new contact could not be
 * encrypted at all.
 *
 * What it reveals is that an account exists and how many devices it has. Both
 * are already inferable from being able to message someone.
 */
drop policy if exists "device keys are public" on public.device_keys;
create policy "device keys are public"
  on public.device_keys for select
  to authenticated
  using (true);

-- You may only ever publish, update or withdraw your own device.
drop policy if exists "own device keys" on public.device_keys;
create policy "own device keys"
  on public.device_keys for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "update own device keys" on public.device_keys;
create policy "update own device keys"
  on public.device_keys for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "delete own device keys" on public.device_keys;
create policy "delete own device keys"
  on public.device_keys for delete
  to authenticated
  using (user_id = auth.uid());

/*
 * Live, because a new device must be reachable immediately.
 *
 * Somebody installing PINGO on a second phone and being told to wait for the
 * other party to reload before messages arrive is not a thing that would ever
 * be forgiven, and it is precisely what a non-published table would cause.
 */
do $$
begin
  alter publication supabase_realtime add table public.device_keys;
exception
  when duplicate_object then null;
end;
$$;
